### ISSUE TITLE
Override default IPFS gateway

### ISSUE THREAD

**Issue by KBryan** [tokenbound/iframe#36]
Great tool. Is there a way to override the default IPFS gateway? I'm currently using Pinata and would like to use that instead. I'm looking for where in the code this needs to be updated. Thanks in advance.

**Comment by KBryan** [comment]
Seems the issue I was having was with my local ipfs node.

**Comment by huynhr** [comment]
@KBryan hey sorry for getting back late on this. Glad it worked out!
